### ISSUE TITLE
FPU option not set in exported IAR project files for several platforms 

### ISSUE THREAD

**Issue by maclobdell** [project-generator/project_generator_definitions#100]
I'm using:
IAR EWARM 7.40.7
mbed-os-5.1.0-rc4
project-generator (0.9.8)
project-generator-definitions (0.2.27)

Exporting to the following targets and trying to build in IAR IDE results in an error that the device doesn't have VFP registers.  The project files need to have the FPU option set to VFPv4 single precision.  
NUCLEO_F411RE
NUCLEO_F401RE
DISCO_F429ZI
FRDM-K64F
FRDM-K22F

**Comment by 0xc0170** [comment]
I left a comment in the referenced issue. This is not an issue for progen, rather for mbed. mbed uses IAR template generated by IAR 7.40.2 or even lower. Therefore this contains old IAR syntax that was changed in newer versions. 

Progen checks if a target supports newer versions, and switches a template to use newer one. Or if a template provided contains newer syntax. In this case, mbed uses old one, target uses old one, thus a project is generated for >7.40.3. To switch to newer versions, either target would require an update or a template used (in this case mbed IAR template).

mcu K22 that is for frdm-k22f defines old IAR definition https://github.com/project-generator/project_generator_definitions/blob/master/project_generator_definitions/mcu/freescale/mk22dn512xxx5.yaml#L23 . 

We need to start thinking about versioning mcu definitions somehow with tools.

**Comment by 0xc0170** [comment]
Closed as resolved, not relevant anymore
