### ISSUE TITLE
STM32/IAR: make UseFlashLoader option enabled by default

### ISSUE THREAD

**Issue by jeromecoutant** [project-generator/project_generator_definitions#107]
Hi
When I export MBED test for a NUCLEO_STM32 targets and IAR,
I always need to change project option within the IDE to use flash loader in the Debugger/Download options.

Maybe it can be automatic by changing yaml files ?

Thx

**Comment by 0xc0170** [comment]
Thanks for the reporting. The use of flash loader is not yet defined here. It should be possible as some MCU requires it or some do not.
