### ISSUE TITLE
Support for Cortex-M33

### ISSUE THREAD

**Issue by mmahadevan108** [project-generator/project_generator_definitions#126]
Is there plan to add support for Cortex-M33

**Comment by 0xc0170** [comment]
Hi @mmahadevan108 , I can have a look to be added in the next week

**Comment by 0xc0170** [comment]
Do you get an error in the IDE or progen asserts? What tools should be covered? I assume uvision (armc6) ?

I haven't tested myself IAR 8.

**Comment by mmahadevan108** [comment]
I am using for FlashAlgo project, uvision please.

**Comment by 0xc0170** [comment]
I'll have a look. It would be good to provide a project (yaml files) to show me the failure, so I can quickly reproduce the problem and fix it

**Comment by 0xc0170** [comment]
I'll add cortex-m33 now

**Comment by 0xc0170** [comment]
I created PR, @mmahadevan108 please review (if you can test locally and confirm it works, that would be really great)

**Comment by 0xc0170** [comment]
PR integrated but not yet released neither this one closed until confirmed it works

**Comment by 0xc0170** [comment]
Closing as resolved
