### ISSUE TITLE
Create tags

### ISSUE THREAD

**Issue by kylemanna** [project-generator/project_generator_definitions#32]
Hi,

I'm working to package this up for Arch Linux and am curious if you can create tags to the releases so I can build the packages based on tags.

Thanks!

**Comment by 0xc0170** [comment]
Thanks for this.

I just pushed the last tag (v0.1.4 for dev_v1 branch. The previous versions had some problems, thus I did not push any tags. I consider v0.1.4 as a starting point, means - I'll be pushing tags from now on
