### ISSUE TITLE
Cortex-M0+ MCU support?

### ISSUE THREAD

**Issue by toyowata** [project-generator/project_generator_definitions#49]
I could not find Cortex-M0+ definition here:
https://github.com/project-generator/project_generator_definitions/tree/master/project_generator_definitions/mcu/arm

Is there any particular reason not to have this?

**Comment by 0xc0170** [comment]
It has not been added, you can send PR adding it.

**Comment by toyowata** [comment]
Thanks.

**Comment by 0xc0170** [comment]
I'll reopen it, as this should be fixed (=added) ;)
