### ISSUE TITLE
uvision5 for NUCLEO_F746ZG: flasholoader not set

### ISSUE THREAD

**Issue by adustm** [project-generator/project_generator_definitions#83]
Hello,
When I export a project for NUCLEO_F746ZG it does not contain the correct information for flash
`mbed export -i uvision5 -m NUCLEO_F746ZG --source=mbed-os/TESTS/mbed_drivers/c_strings
`
The correct value seems to be in the <projectname>.uvoptx file

```
          <Number>0</Number>
          <Key>UL2CM3</Key>
          <Name>UL2CM3(-S0 -C0 -P0 -FD20010000 -FC1000 -FN1 -FF0STM32F7x_1024 -FS08000000 -FL0100000 -FP0($$Device:STM32F746ZG$CMSIS\Flash\STM32F7x_1024.FLM))</Name>

```

Could you fix it, please ?
Cheers

**Comment by 0xc0170** [comment]
Thanks for reporting. We will need to check the uvoptx file, and how to add the required details for debuggers

**Comment by 0xc0170** [comment]
I merged one PR that fixed F411  https://github.com/project-generator/project_generator_definitions/pull/98 

Regarding progen, there is already support for uvopt/x file . I'll close this PR. Please reopen if the issue persists (some targets might not have correct flash algo values, please send PR if that's the case).
